name: aicc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=11.0
  - pytorch==1.7.1
  - torchaudio==0.7.2
  - torchvision==0.8.2
  - scikit-learn
  - opencv
  - matplotlib